#!/usr/bin/env node

/**
 * Security Report Generator — Antigravity Sub-Agent
 *
 * Generuje Markdown report z JSON výstupu security-scan.js
 *
 * Použitie:
 *   node scripts/generate-report.js security-scan-report.json
 */

const fs = require('fs');
const path = require('path');

const inputPath = process.argv[2];

if (!inputPath) {
  console.error('Použitie: node generate-report.js <security-scan-report.json>');
  process.exit(1);
}

const report = JSON.parse(fs.readFileSync(inputPath, 'utf8'));

const severityEmoji = {
  CRITICAL: '🔴',
  HIGH: '🟠',
  MEDIUM: '🟡',
  LOW: '🔵',
  INFO: '⚪'
};

let md = `# 🔒 Security Audit Report

**Date:** ${new Date(report.timestamp).toLocaleDateString('sk-SK')}
**Project:** ${report.projectDir}
**Files Scanned:** ${report.filesScanned}

## Executive Summary

| Metric | Value |
|--------|-------|
| **Overall Risk** | **${report.overallRisk}** |
| 🔴 Critical | ${report.counts.CRITICAL} |
| 🟠 High | ${report.counts.HIGH} |
| 🟡 Medium | ${report.counts.MEDIUM} |
| 🔵 Low | ${report.counts.LOW} |
| ⚪ Info | ${report.counts.INFO} |
| **Total** | **${report.findings.length}** |

`;

// Group by severity
for (const severity of ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO']) {
  const items = report.findings.filter(f => f.severity === severity);
  if (items.length === 0) continue;

  md += `## ${severityEmoji[severity]} ${severity} (${items.length})\n\n`;

  items.forEach((finding, idx) => {
    const id = `${severity[0]}-${String(idx + 1).padStart(3, '0')}`;
    md += `### ${id}: ${finding.message}\n\n`;
    md += `- **Category:** ${finding.category}\n`;
    if (finding.file) {
      md += `- **File:** \`${finding.file}${finding.line ? ':' + finding.line : ''}\`\n`;
    } else {
      md += `- **Scope:** Project-wide\n`;
    }
    if (finding.fix) {
      md += `- **Fix:** ${finding.fix}\n`;
    }
    md += '\n';
  });
}

md += `## Recommendations

### Immediate Actions (Critical & High)
${report.findings.filter(f => ['CRITICAL', 'HIGH'].includes(f.severity)).map(f => `- ${f.fix || f.message}`).join('\n') || '- No critical/high findings — great job!'}

### Short-term (Medium)
${report.findings.filter(f => f.severity === 'MEDIUM').map(f => `- ${f.fix || f.message}`).join('\n') || '- No medium findings'}

### Nice to Have (Low)
${report.findings.filter(f => f.severity === 'LOW').map(f => `- ${f.fix || f.message}`).join('\n') || '- No low findings'}

---

*Generated by Next.js Security Audit Agent — Antigravity*
`;

const outputPath = inputPath.replace('.json', '.md');
fs.writeFileSync(outputPath, md);
console.log(`✅ Report generated: ${outputPath}`);
